// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7hDI1vrye4aES9dxFqziY42T_lOeucPs',
    appId: '1:19627154259:web:7a9a058ca0f4e614c4dfa6',
    messagingSenderId: '19627154259',
    projectId: 'stclub-69325',
    authDomain: 'stclub-69325.firebaseapp.com',
    storageBucket: 'stclub-69325.appspot.com',
    measurementId: 'G-2CL3QR9ZYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LfiSYBsdHn1sTBpaHyxMiVZfbZXH8dk',
    appId: '1:19627154259:android:871445ced84e3196c4dfa6',
    messagingSenderId: '19627154259',
    projectId: 'stclub-69325',
    storageBucket: 'stclub-69325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ISbqzHN5YyORBAoA69RAEVP3eBl5gkE',
    appId: '1:19627154259:ios:421bfa73080a0e77c4dfa6',
    messagingSenderId: '19627154259',
    projectId: 'stclub-69325',
    storageBucket: 'stclub-69325.appspot.com',
    iosClientId: '19627154259-f1pivnsa9jk83ailc6hrarpfl7agmcoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.stClub',
  );
}
